### ISSUE TITLE
Support for CommonJS?

### ISSUE THREAD

**Issue by niksy** [newoga/babel-plugin-transform-replace-object-assign#1]
Currently, transform expects that final code uses ES modules, but maybe there could be option to switch to CommonJS `require`?

Code for `require` would look something like this:

```js
const declar = t.variableDeclaration('var', [t.variableDeclarator(t.identifier(OBJECT_ASSIGN), t.callExpression(t.identifier('require'), [t.stringLiteral(OBJECT_ASSIGN)]))]);
```

What do you think? I could create PR for this if you’re interested.

**Comment by newoga** [comment]
@niksy I apologize for the late response, I am just seeing this now.

I'm not against the change you are suggesting, however I am curious about what you are using this project for. The reason why I'm asking is because I was just recently planning on formally deprecating this project on npm as a lot has changed since this project was created and the primary motivation that lead to me creating this project was an bug in Chrome that was fixed.

Thanks for your interest and contributing in open source 😄

**Comment by niksy** [comment]
@newoga it’s for the projects which don’t use ES imports and can benefit from not including same code in every file. Granted, there will be less and less projects over time like that, but it can be useful when publishing transpiled code for package and smaller output.

I can create PR if you’re interested.

**Comment by newoga** [comment]
@niksy Hey, sorry again for the late response. My email still gets overwhelmed from github emails relating to the material-ui project. If this change still has value for you, I'd be glad to accept a PR for it and release a new version.
